{% set name = "tkinterweb" %}
{% set version = "3.18.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tkinterweb-{{ version }}.tar.gz
  sha256: bb2113b228bd7ed227d508fc9348446061549f7406b913a4c098384bea9e4dea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - pillow >=7.1

test:
  imports:
    - tkinterweb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Andereoo/TkinterWeb
  summary: HTML/CSS viewer for Tkinter - bindings for Tkhtml3
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - Andereoo
